---
name: Integration Tests
on:
  pull_request:
    paths:
      - "action.yaml"
      - ".github/workflows/integration-tests.yaml"

jobs:
  test:
    name: Test ${{ matrix.commit.title }}
    # These permissions are needed to:
    # - Checkout the repo
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        commit:
          - title: Merge Commit
            sha: ${{ github.sha }}
          - title: Head Commit
            sha: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.commit.sha }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/beacon-biosignals/whalesay
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: ./
        id: build
        with:
          image-repository: ghcr.io/beacon-biosignals/whalesay
          context: test
          build-args: |
            DEBIAN_VERSION=12.9
      - name: Validate image works
        run: |
          docker pull "${{ steps.build.outputs.image }}"
          output="$(docker run "${{ steps.build.outputs.image }}")"
          if [[ "$(wc -l <<<"$output")" -lt 15 ]]; then
              echo "$output"
              exit 1
          fi
          debian_version="$(docker run --entrypoint=/bin/cat "${{ steps.build.outputs.image }}" /etc/debian_version)"
          [[ "$debian_version" == "12.9" ]] || exit 2
      - name: Validate cache images
        run: |
          docker manifest inspect "${{ steps.build.outputs.image-repository }}:cache-sha-${{ matrix.commit.sha }}"
          docker manifest inspect "${{ steps.build.outputs.image-repository }}:cache-branch-${branch//[^[:alnum:]]/_}"
        env:
          branch: ${{ github.head_ref || (github.ref_type == 'branch' && github.ref_name) }}"
      - name: Validate annotations
        run: |
          set -x
          json="$(docker manifest inspect "${{ steps.build.outputs.image }}")"
          [[ "$(jq -r '.annotations."org.opencontainers.image.revision"' <<<"$json")" == "${{ matrix.commit.sha }}" ]] || exit 1
